### ISSUE TITLE
Can access registration page with the direct link when not logged in

### ISSUE THREAD

**Issue by adammichalik** [Pragmatists/OpenTrapp#40]
Even if I'm not logged in, I can go to
http://pragmatists.github.io/OpenTrappUI/#/registration
and try to register time. I get an error message "Server not responding" when I submit the form.

**Comment by michal-lipski** [comment]
https://github.com/Pragmatists/OpenTrappUI/commit/628bab8c36273f52595a41b2d2b926206198bcd9
