### ISSUE TITLE
Use moment("date string", "date format") instead of moment("date string")

### ISSUE THREAD

**Issue by adammichalik** [Pragmatists/OpenTrapp#63]
MomentJS now issues this warning:

```
WARN: 'Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release.
Please refer to https://github.com/moment/moment/issues/1407 for more info.'
```

According to the [more info](https://github.com/moment/moment/issues/1407) link, we should be using the `moment("date string", "date format")` instead `moment("date string")` for reliable moment creation.

**Comment by cmsabelita** [comment]
how?

**Comment by bob360** [comment]
One of the biggest trouble is dealing with dates with mongodb, moment ,ISO..Moment was suppose to be a package that help deal with dates,but at the end its just adding more trouble.I have been struggling for two days just to add 30 days to the currentdate and <moment().add(30, 'days')> keeps on showing the deprecation warning.This is insane.
