### ISSUE TITLE
I would like to see my total registered time for current month on "Register time" page

### ISSUE THREAD

**Issue by apierzch** [Pragmatists/OpenTrapp#85]
It would be helpful to always see the same row that I see for myself in "Reports" page, for all eligible projects with calendar view. Something like attached pseudo-screenshot.
![screenshot from 2014-06-17 08 31 51](https://cloud.githubusercontent.com/assets/4123582/3296987/a6e262ae-f5e9-11e3-9283-b4e768ade548.png)

**Comment by michal-lipski** [comment]
Fixed in: https://github.com/Pragmatists/OpenTrappUI/commit/f549eefe186d9b009903fe97023fbe5e551221b9
