### ISSUE TITLE
No access to future months

### ISSUE THREAD

**Issue by nkoder** [Pragmatists/OpenTrapp#88]
I've reported plan for my vacation in December 2014 (now is July 2014).
Now I don't' have any possibility to see it reported, because there are only May, June, July, and August visible.

**Comment by michal-lipski** [comment]
https://github.com/Pragmatists/OpenTrappUI/commit/930f6db21bce4afdb83daa43930c86ee55a522a3
https://github.com/Pragmatists/OpenTrappUI/commit/90824ec50f3a4d1d80459a9a45e9ce17bbec4b5d
