### ISSUE TITLE
Registration page looks like there is no content below "report" and "examples" headers

### ISSUE THREAD

**Issue by nkoder** [Pragmatists/OpenTrapp#94]
I was pretty sure that there is no content in "Reports" and "Examples" sections on the registration page. After some clicking it appeared that now these headers are folded and content can be shown.
In my opinion it is totally unintuitive but I understand that there are many different opinions :-)

This "bug" is probably effect of #85 

Screenshot: ![Screenshot]( http://i.imgur.com/OtRQ9QD.png )

**Comment by mpi** [comment]
1. Let's reveal Report section by default and rename it to My Worklog for 2015/02.
2. Let's move Examples section to separate page/modal and link it from registration page by "?" / "help" icon.

**Comment by michal-lipski** [comment]
Fixed by: https://github.com/Pragmatists/OpenTrappUI/commit/207c0467fb1b672cd46af2981875533f53f7fa15
https://github.com/Pragmatists/OpenTrappUI/commit/7e9e36e3473b52942198c8e22dbcb2b8fbe9b033
